name: Test pull request changes

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello world its me from a pull request

      - name: setup node.js env
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "20.x"
      - run: node --version

      - name: prepare environment
        run: |
          npm ci
      - name: run test
        run: npm run test
